name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cmake-build:
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          build: [static]
          generator: ["Default Generator", "Unix Makefiles"]
      env:
        CMAKE_GENERATOR: >-
          ${{format(matrix.generator != 'Default Generator' && '-G "{0}"' || '', matrix.generator)}}
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2

        - name: Get number of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1

        - name: Build
          shell: bash
          run: |
            cmake ${{ env.CMAKE_GENERATOR }} -S "${{ github.workspace }}" -B build
            cd build && cmake --build . --parallel ${{ steps.cpu-cores.outputs.count }}
            
        - name: Build Tests
          shell: bash
          run: |
            cmake ${{ env.CMAKE_GENERATOR }} -S "${{ github.workspace }}" -B build
            cd build && cmake --build . --parallel ${{ steps.cpu-cores.outputs.count }}
        - name: Run Tests
          shell: bash
          run: |
            cd build && ctest -C Debug --output-on-failure --verbose
